[package]
name = "mhdb"
version = "0.1.0"
authors = ["mhmorgan <mhmorgan42@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
serde = { version = "1.0.111", features = ["derive"] }
bincode = "1.2.1"